### ISSUE TITLE
Logging in after redirect from cart does not redirect back to cart.

### ISSUE THREAD

**Issue by rversteegt** [roeldewit/PSE#33]
When a user attempts to place an order without logging in, he is redirected to the login page. After logging in it would be nice to either redirect back to the shopping cart, or immediately place the order and continue to payment.

**Comment by rversteegt** [comment]
See branch issue#33. I added a redirect url to the login page request. Looking for someone to catch that on the login page, and redirecting after having logged in.

**Comment by gijshendrikx** [comment]
Catch on login page is not very easy. Looks like it can be done by adding an attribute to a authentication session on the time of login and using that to redirect, not sure it will work and it will take some time to implement.

An easier and cleaner solution might be to protect the page a customer should finally enter?

When "/app/payment/pay/" + order_id" is protected by ROLE_CUSTOMER the login screen will be forced and redirect will take place directly to the payment page instead of the cart page again. Would this work?

**Comment by ghost** [comment]
Sounds good.

-----Oorspronkelijk bericht-----
Van: "gijshendrikx" notifications@github.com
Verzonden: ‎26-‎11-‎2015 22:07
Aan: "roeldewit/PSE" PSE@noreply.github.com
Onderwerp: Re: [PSE] Logging in after redirect from cart does not redirect backto cart. (#33)

Catch on login page is not very easy. Looks like it can be done by adding an attribute to a authentication session on the time of login and using that to redirect, not sure it will work and it will take some time to implement.
An easier and cleaner solution might be to protect the page a customer should finally enter?
When "/app/payment/pay/" + order_id" is protected by ROLE_CUSTOMER the login screen will be forced and redirect will take place directly to the payment page instead of the cart page again. Would this work?

**Comment by gijshendrikx** [comment]
Fixed
